[package]
name = "mmuvp_ecs_3_0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.29"
rand = "0.8"
serde = "1.0"
serde_json = "1.0"
statrs = "0.14"
rayon="1.5"